git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

os:
  edit: 'hx {{filename}}'
  editAtLine: 'hx {{filename}}:{{line}}'
  editAtLineAndWait: 'hx {{filename}}:{{line}}'
  editInTerminal: true
  openDirInEditor: 'hx {{dir}}'
