coral_data:
  price_database:
    server: VM-UKS-MODSQL01
    database: PriceDB
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: true
  powerbi_database:
    server: VM-UKS-MODSQL01
    database: EMAPowerBI
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: true
  emt_results_database:
    server: VM-UKS-MODSQL01
    database: EMT-Plexos-Results
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: true
  ema_reports_database:
    server: VM-UKS-MODSQL01
    database: EMAReports
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: true
  us_ema_powerbi_database:
    server: azsqlmiuksema.eb8621385ce2.database.windows.net
    database: US-EMAPowerBI-DEV
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: false
  historical_data_database:
    server: VM-UKS-MODSQL01
    database: HistoricalData
    driver: ODBC Driver 17 for SQL Server
    credentials: null
    trusted_connection: true
  quarter_to_scenario_to_run:
    2023Q3:
      REFERENCE: v925_LT1_ST1_PT2209_Ref
      LOW: v925_LT1_ST1_PT2209_Low
      NET_ZERO: v925_LT1_ST1_PT2209_NZ
      NET_ZERO_HIGH: v925_LT1_ST1_PT2209_NZHigh
    2023Q4:
      REFERENCE: v932_LT1_ST1_PT2209_Ref
      LOW: v932_LT1_ST1_PT2209_Low
      NET_ZERO: v932_LT1_ST1_PT2209_NZ
      NET_ZERO_HIGH: v932_LT1_ST1_PT2209_NZHigh
    2024Q1:
      REFERENCE: v960_LT1_ST1_Ref
      LOW: v960_LT1_ST1_Low
      NET_ZERO: v960_LT1_ST1_NZ
      NET_ZERO_HIGH: v960_LT1_ST1_NZHigh
  shared_files:
    fx_rate_files:
      2023Q3: L:/Internal projects/Market models/1_Pan EU/27_2023_Q3/1_PLEXOS/v925/LT1_ST1_PT2209/3_Fuel
        Prices/AllFX.csv
      2023Q4: L:/Internal projects/Market models/1_Pan EU/28_2023_Q4/1_PLEXOS/v932/LT1_ST1_PT2209/3_Fuel
        Prices/AllFX.csv
      2024Q1: X:/Internal projects/PanEU/1_2024_Q1/v960/LT1_ST1/3_Fuel Prices/AllFX.csv
  cache_directory: /tmp
  cache_ttl_seconds: 43200
  local_cache: true
  entsoe_api_key: Missing
  esios_api_key: Missing
  current_quarter: 2024Q1
  plexos_system_path: C:\Program Files\Energy Exemplar\PLEXOS 8.3
  generator_fuel_config_path: ''
  generator_bid_config_path: ''
