[shell_alias]
qa="nox -s quality-3.12"
nvim="~/.local/bin/maybe_nvim.sh"
vi="~/.local/bin/maybe_nvim.sh"
pt="uv run pytest -v"
py="ptpython"

[env]
_.python.venv = { path = ".venv", create = true }

[hooks]
enter = "uv pip install pytest-pudb-resurrected ptpython"

[tasks.bootstrap]
description = "bootstrap this worktree"
alias = "bs"
run = [
	'uv sync',
	'pre-commit install',
    'git commit --allow-empty --no-verify -m "$(basename "$PWD")"'
]
