[shell_alias]
py="ptpython"

# cd into the root of the git folder.
r='cd $(git rev-parse --show-toplevel)'

# find pytest tests using fzf
pts='source ~/repos/dotfiles/scripts/pts.zsh'

[env]
_.python.venv = { path = ".venv", create = true }

[hooks]
enter = "uv pip install pytest-pudb-resurrected ptpython"

[tasks.bootstrap]
description = "bootstrap this worktree"
alias = "bs"
run = [
	'uv sync',
	'pre-commit install',
    'git commit --allow-empty --no-verify -m "$(basename "$PWD")"'
]
