theme = "tokyonight_night"

[platform]
windows.shell = {program="wsl", args = ["--cd","~"]}

[window]
decorations = "Disabled"

[keyboard]
use-kitty-keyboard-protocol = true

[fonts]
family = "FiraCode Nerd Font Mono"
size = 14
features = ["-calt","-liga","cv01=2"]
hinting= false

[navigation]
mode = "Plain"
use-split = false

[bindings]
keys = [
{key="tab", with = "control", esc="\u001b[27;5;9~"},
{key="tab", with = "control | shift", esc="\u001b[27;6;9~"}
]

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.rules]]
regex = "([\\w./-]+\\.\\w+(?::\\d+(?::\\d+)?)?)|([\\w./-]+::\\w+(?:\\[[^\\]]*\\])?)"
post-processing = true
action = "Paste"

[hints.rules.binding]
key = ""
mods = ["Control", "Shift"]
