# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=10000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

export LESS='--chop-long-lines --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'

# # enable color support of ls and also add handy aliases
# if [ -x /usr/bin/dircolors ]; then
#     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#     alias ls='ls --color=auto'
#     #alias dir='dir --color=auto'
#     #alias vdir='vdir --color=auto'

#     alias grep='grep --color=auto'
#     alias fgrep='fgrep --color=auto'
#     alias egrep='egrep --color=auto'
# fi


# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gco="git checkout"
alias gp="git push"
alias gpf="git push --force-with-lease --force-if-includes"
alias grbc="git rebase --continue"


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='code --wait'
fi
export PIP_REQUIRE_VIRTUALENV=true



## EVALS and executions.
source ~/repos/fzf-git.sh/fzf-git.sh

eval "$("$HOME"/bin/fzf --bash)"
eval "$(/usr/local/bin/starship init bash)"
eval "$(direnv hook bash)"

# open repos using fzf
alias vc='source ~/repos/dotfiles/scripts/vc.sh'

# cd into the root of the git folder.
alias r='cd $(git rev-parse --show-toplevel)'

# use fzf to find a file starting at the current folder, ignoring any folder starting with "." (a dotted folder being a private folder.)
alias ff="find . -type f -not -path '*/\.*/*' | fzf --preview 'batcat {}'"

#AI? this function is copied over from an .zshrc file. But in bash it isn't working
pts() {
    local selected_test
    selected_test=$(~/repos/dotfiles/scripts/list_tests.sh tests | fzf)
    if [[ -n "$selected_test" ]]; then
      
          print -z "uv run pytest $selected_test"
    fi
}

# . "$HOME/.local/bin/env"

# export PATH="$HOME/repos/dotfiles/scripts:$PATH:$HOME/bin:$HOME/.local/bin:"
# PATH="$HOME/repos/dotfiles/scripts:$PATH"

source /home/sander/.config/broot/launcher/bash/br
