---
- hosts: localhost
  connection: local
  become: yes

  pre_tasks:
    - name: pre-run | update package cache (ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install packages from apt
    package:
      name:
      - htop
      - eget