[tools]
"aqua:micro-editor/micro" = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
"github:neurocyte/flow" = "latest"
"github:sinelaw/fresh" = "latest"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
mprocs = "latest"
opencode = "latest"
taplo = "latest"
watchexec = "latest"

[settings]
experimental = true
