[tools]
"aqua:micro-editor/micro" = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fnox = "latest"
"github:1broseidon/cymbal" = "latest"
"github:neurocyte/flow" = "latest"
helix = "latest"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
mprocs = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pi = "latest"
taplo = "latest"
television = "latest"
tree-sitter = "latest"
watchexec = "latest"
yazi = "latest"
zellij = "latest"

[settings]
experimental = true
