[tools]
bat = "latest"
eza = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
"github:1broseidon/cymbal" = "latest"
"github:atanunq/viu" = "latest"
helix = "latest"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pi = "latest"
ripgrep = "latest"
starship = "latest"
taplo = "latest"
tmux = "3.6b"
tree-sitter = "latest"
yazi = "latest"
zellij = "latest"

[settings]
experimental = true
